### ISSUE TITLE
Caught unexpected exception in kb/Query

### ISSUE THREAD

**Issue by gabrielslau** [Idilia/idilia-api-samples#3]
Hi,

The kb/Query basic example is throwing this message:
`Caught unexpected exception: Invalid Date header. Must have format: %a, %d %b %Y %H:%M:%S %Z in UTC time zone. Received: Seg, 11 abr 2016 06:41:25 GMT`

I've seen that the com.idilia.services.base.RequestSigner class is the only file that sets a GMT TimeZone but there is no way to customize it.

There is some other configuration to do besides the credentials?

**Comment by pierrebelzile** [comment]
It's the locale. It has to be set to English because we are expecting an English date (e.g., Mon, 11 Apr 2016 06:41:25 GMT). I consider this a bug on our side because we should always generate an English date no matter what your VM's locale is.

Expect an update. In the meanwhile, you can set the locale.

**Comment by pierrebelzile** [comment]
We have just published an update to the java SDK that should fix your problem. The new pom version is 1.1.10. It will appear in mvn central soon.

Thanks for pointing this out.
